### ISSUE TITLE
Cloud Composer authentication

### ISSUE THREAD

**Issue by soniaCarl2022** [TIBCOSoftware/cic-cli-core#9]
Hello, I tried to start locally Cloud Composer by using tcli but I can't access. My ClientID and TIBCO Cloud credentials are never accepted.

**Comment by varpatil-tibco** [comment]
This issue belongs to the Cloud Composer CLI. Please raise it [here](https://github.com/TIBCOSoftware/TCSTK-Cloud-CLI).
